In [8]:
import numpy as np

array([12, 23, 34, 35, 45, 78])

In [34]:
a = np.array([12, 23, 34, 35, 45, 78])
a

np.int64(12)

In [13]:
b = np.array([[1, 2, 7], [3, 4, 5]])
b

array([[1, 2, 7],
       [3, 4, 5]])

In [23]:
m = np.array([[1, 2.5, 4.67, 9.0], [90, 78, 7.8, 25]])
m

array([[ 1.  ,  2.5 ,  4.67,  9.  ],
       [90.  , 78.  ,  7.8 , 25.  ]])

In [24]:
m.shape

(2, 4)

In [25]:
type(m)

numpy.ndarray

In [26]:
m.dtype

dtype('float64')

In [15]:
z = np.zeros(5) #массив из нулей
z

array([0., 0., 0., 0., 0.])

In [16]:
o = np.ones((4, 5)) #двумерный массив из единиц, размером 4 на 5
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
r = np.arange(0, 20, 3) #массив от 0 до 20 с шагом 3
r

array([ 0,  3,  6,  9, 12, 15, 18])

In [19]:
e = np.eye(3) #единичная матрица размером 3 на 3
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
em = np.empty((3, 5))
em

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.81019663e-310]])

In [27]:
test_ar = np.arange(0, 100, 10)
test_ar

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
#по отдельности выводим первый эл массива, последний и пятый
print(test_ar[0]) 
print(test_ar[-1])
print(test_ar[4])

0
90
40


In [36]:
print(test_ar[2:6]) #со второго по пятый эл
print(test_ar[::2]) # каждый второй эл
print(test_ar[3:]) # с третьего эл и до конца
print(test_ar[:2]) #с начала и до первого эл 

[20 30 40 50]
[ 0 20 40 60 80]
[30 40 50 60 70 80 90]
[ 0 10]


In [37]:
t1 = np.array([1, 2, 4, 6, 7])
t1

array([1, 2, 4, 6, 7])

In [38]:
t2 = np.arange(0, 10, 2)
t2

array([0, 2, 4, 6, 8])

In [39]:
s = t1+t2
s

array([ 1,  4,  8, 12, 15])

In [40]:
d = t1-t2
d

array([ 1,  0,  0,  0, -1])

In [41]:
m = t1*t2
m

array([ 0,  4, 16, 36, 56])

In [42]:
p = t1**t2
p

array([      1,       4,     256,   46656, 5764801])

In [43]:
print(t1*2)
print(t2+11)

[ 2  4  8 12 14]
[11 13 15 17 19]


In [44]:
print(np.sqrt(t1))
print(np.exp(t2))

[1.         1.41421356 2.         2.44948974 2.64575131]
[1.00000000e+00 7.38905610e+00 5.45981500e+01 4.03428793e+02
 2.98095799e+03]


In [45]:
a = np.array([2, 5, 3, 6, 7, 4, 0, 1, 4, 5, 6, 8])
a

array([2, 5, 3, 6, 7, 4, 0, 1, 4, 5, 6, 8])

In [48]:
print(np.mean(a)) #среднее
print(np.median(a)) #медиана
print(np.std(a)) #стандартное отклонение
print(np.var(a)) #дисперсия
print(np.min(a)) #минимальное
print(np.max(a)) #максимальное
print(np.sum(a)) #сумма

4.25
4.5
2.3139072294858036
5.354166666666667
0
8
51


In [50]:
b = np.array([[1, 2], [3, 4], [5, 6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
print(np.mean(b))
print(np.mean(b, axis = 1)) #среднее по строкам
print(np.mean(b, axis = 0)) #среднее по столбцам

3.5
[1.5 3.5 5.5]
[3. 4.]
